### PR TITLE
efix(extension): Allow requests to reach the language server when in c…

### LINKED ISSUE #2064: quick info stops working if there are two components in the same file and I change a field in parent component
# 🐞 bug report

### Description

https://github.com/angular/vscode-ng-language-service/assets/25394362/a30843f3-e7c5-4106-b8a3-4c676389963e

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

**Expected behavior**

Quick info to not stop working

### PR DESCRIPTION
**Pull request by atscott**
…omponent decorator

This commit updates the early-return logic on the client-side to allow requests to go to the server whenever the cursor is inside the component decorator. Prior to this change, some requests would attempt to return early if the position was not inside the inline template region. However, we were never able to get the tokenizing working correctly and this has led to issues whenever there are multiple template strings (JS template strings with \`).

This approach should give us the needed benefits of early-returns in non-Angular contexts (`@Component` decorator should be pretty rare) while being more permissive and correct.

fixes #2064

### CODE REVIEW

File: client/src/client.ts [hunk 1]
```diff
@@ -67,8 +67,8 @@ export class AngularLanguageClient implements vscode.Disposable {
             document: vscode.TextDocument, range: vscode.Range, context: vscode.CodeActionContext,
             token: vscode.CancellationToken, next: lsp.ProvideCodeActionsSignature) => {
           if (await this.isInAngularProject(document) &&
-              isInsideInlineTemplateRegion(document, range.start) &&
-              isInsideInlineTemplateRegion(document, range.end)) {
+              isInsideComponentDecorator(document, range.start) &&
+              isInsideComponentDecorator(document, range.end)) {
```
Comment (devversion) [inline client/src/client.ts:71]: The function seems to also return for HTML files, but the name only suggests "inside decorator". Wondering if we can rename, but otherwise LGTM.

**Review by devversion — APPROVED** [review]
