### PR TITLE
fix: reset loading status when the language service fails to load the project.

### LINKED ISSUE #464: "Initializing Angular language features" remains pending in VS Code 1.40.2
**Describe the bug**

After the update of Visual Studio Code from 1.40.1 to 1.40.2, in the bottom left the message "Initializing Angular language features" is stuck and the language features don't get enabled.

**To Reproduce**

1. Install VS Code 1.40.1 and install the Angular Language Features plugin
2. Update to VS Code 1.40.2

**Expected behavior**

The plugin to actually work in the latest VS Code update

**Logs**

Please attach two logs:

In the output console I see:

> [Info  - 9:48:35 AM] Angular language server process ID: 82460
> [Info  - 9:48:35 AM] Using typescript v3.6.4 from /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/node_modules/typescript/lib/tsserverlibrary.js
> [Info  - 9:48:35 AM] Using @angular/language-service v9.0.0-rc.3 from /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/server/node_modules/@angular/language-service/bundles/language-service.umd.js
> [Info  - 9:48:35 AM] Log file: /Users/cristiantraina/Library/Application Support/Code/logs/20191126T100445/exthost7/Angular.ng-template/nglangsvc.log
> Warning: Can't resolve all parameters for OpaqueToken in /Users/cristiantraina/Documents/workspaces/project/EVOL_C/node_modules/@angular/core/src/di/opaque_token.d.ts: (?). This will become an error in Angular v6.x
> Warning: Can't resolve all parameters for TemplateParser in /Users/cristiantraina/Documents/workspaces/project/EVOL_C/node_modules/@angular/compiler/src/template_parser/template_parser.d.ts: ([object Object], [object Object], [object Object], ?, [object Object]). This will become an error in Angular v6.x
> Warning: Can't resolve all parameters for DirectiveWrapperCompiler in /Users/cristiantraina/Documents/workspaces/project/EVOL_C/node_modules/@angular/compiler/src/directive_wrapper_compiler.d.ts: ([object Object], [object Object], [object Object], ?). This will become an error in Angular v6.x
> Warning: Can't resolve all parameters for DirectiveResolver in /Users/cristiantraina/Documents/workspaces/project/EVOL_C/node_modules/@angular/compiler/src/directive_resolver.d.ts: (?). This will become an error in Angular v6.x
> Warning: Can't resolve all parameters for NgModuleResolver in /Users/cristiantraina/Documents/workspaces/project/EVOL_C/node_modules/@angular/compiler/src/ng_module_resolver.d.ts: (?). This will become an error in Angular v6.x
> Warning: Can't resolve all parameters for PipeResolver in /Users/cristiantraina/Documents/workspaces/project/EVOL_C/node_modules/@angular/compiler/src/pipe_resolver.d.ts: (?). This will become an error in Angular v6.x
> Warning: Can't resolve all parameters for CompileMetadataResolver in /Users/cristiantraina/Documents/workspaces/project/EVOL_C/node_modules/@angular/compiler/src/metadata_resolver.d.ts: ([object Object], [object Object], [object Object], [object Object], [object Object], [object Object], ?, [object Object]). This will become an error in Angular v6.x
> [Error - 9:48:51 AM] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'attachToProject' of undefined
> 

The log file is:

> Info 0 [9:48:35.276] Format host information updated
> Info 1 [9:48:35.276] reload projects.
> Info 2 [9:48:35.276] Structure before ensureProjectForOpenFiles:
> Info 3 [9:48:35.277] Structure after ensureProjectForOpenFiles:
> Info 4 [9:48:35.277] Host file extension mappings updated
> Info 5 [9:48:35.290] Search path: /Users/cristiantraina/Documents/workspaces/project/EVOL_C/TpdPortalHomeWidget/TpdPortalHomeWidgetWeb/WebContent/modules/le-tue-polizze
> Info 6 [9:48:35.293] For info: /Users/cristiantraina/Documents/workspaces/project/EVOL_C/TpdPortalHomeWidget/TpdPortalHomeWidgetWeb/WebContent/modules/le-tue-polizze/le-tue-polizze.component.html :: Config file name: /Users/cristiantraina/Documents/workspaces/project/EVOL_C/tsconfig.json
> Info 7 [9:48:35.293] Opened configuration file /Users/cristiantraina/Documents/workspaces/project/EVOL_C/tsconfig.json
> Info 8 [9:48:39.137] Loading global plugin @angular/language-service
> Info 9 [9:48:39.137] Enabling plugin @angular/language-service from candidate paths: /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/node_modules/typescript/lib/tsserverlibrary.js/../../..,/Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/server/node_modules/@angular/language-service/bundles/language-service.umd.js
> Info 10 [9:48:39.137] Loading @angular/language-service from /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/node_modules/typescript/lib/tsserverlibrary.js/../../.. (resolved to /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/node_modules/node_modules)
> Info 11 [9:48:39.148] Loading @angular/language-service from /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/server/node_modules/@angular/language-service/bundles/language-service.umd.js (resolved to /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/server/node_modules/@angular/language-service/bundles/language-service.umd.js/node_modules)
> Info 12 [9:48:39.236] Plugin validation succeded
> Info 13 [9:48:39.751] Starting updateGraphWorker: Project: /Users/cristiantraina/Documents/workspaces/project/EVOL_C/tsconfig.json
> Info 14 [9:48:51.101] Search path: /Users/cristiantraina/Documents/workspaces/project/EVOL_C/TpdPortalHomeWidget/TpdPortalHomeWidgetWeb/WebContent/modules/le-tue-polizze
> Info 15 [9:48:51.101] For info: /Users/cristiantraina/Documents/workspaces/project/EVOL_C/TpdPortalHomeWidget/TpdPortalHomeWidgetWeb/WebContent/modules/le-tue-polizze/le-tue-polizze.component.html :: Config file name: /Users/cristiantraina/Documents/workspaces/project/EVOL_C/tsconfig.json
> Info 16 [9:48:51.103] Loading global plugin @angular/language-service
> Info 17 [9:48:51.103] Enabling plugin @angular/language-service from candidate paths: /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/node_modules/typescript/lib/tsserverlibrary.js/../../..,/Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/server/node_modules/@angular/language-service/bundles/language-service.umd.js
> Info 18 [9:48:51.103] Loading @angular/language-service from /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/node_modules/typescript/lib/tsserverlibrary.js/../../.. (resolved to /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/node_modules/node_modules)
> Info 19 [9:48:51.103] Loading @angular/language-service from /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/server/node_modules/@angular/language-service/bundles/language-service.umd.js (resolved to /Users/cristiantraina/.vscode/extensions/angular.ng-template-0.900.0/server/node_modules/@angular/language-service/bundles/language-service.umd.js/node_modules)
> Info 20 [9:48:51.104] Plugin validation succeded
> Info 21 [9:48:51.107] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
> Info 22 [9:48:51.672] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: true Elapsed: 565ms
> Info 23 [9:48:51.672] Project '/dev/null/inferredProject1*' (Inferred)
> Info 24 [9:48:51.672] Files (15)
> 
> Info 25 [9:48:51.672] -----------------------------------------------

### PR DESCRIPTION
**Pull request by andrius-pra**
Currently, the loading indicator remains in pending state when the language service fails to load the project. Typescript project server doesn't send any event when the error occurs.
This commit refactors the loading indicator to reset state when any error occurs while opening the document.

PR closes #464

### CODE REVIEW

File: client/src/project_loading_notification_service.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+  start(): void {
+    this.reset();
+    vscode.window.withProgress(this.options, () => new Promise((resolve) => this.task = {resolve}));
+  }
+
+  finish(): void {
+    this.reset();
+  }
+
+  dispose(): void {
```
Comment (ayazhafiz) [inline client/src/project_loading_notification_service.ts]: Is this method ever used?

File: client/src/extension.ts [hunk 2]
```diff
@@ -12,6 +12,7 @@ import * as vscode from 'vscode';
 import * as lsp from 'vscode-languageclient';
 
 import {registerCommands} from './commands';
+import {ProjectLoadingNotificationService} from './project_loading_notification_service';
 import {projectLoadingNotification} from './protocol';
```
Comment (ayazhafiz) [inline client/src/extension.ts]: Can we put `projectLoadingNotification` and `ProjectLoadingNotificationService` in the same source file?

**Comment by ayazhafiz** [comment]
Could we send a notification to finish the loading indicator in case the language service throws, without the new `ProjectLoadingNotificationService` class

File: client/src/project_loading_notification_service.ts (hunk 1 above)
Comment (andrius-pra) [reply client/src/project_loading_notification_service.ts]: yes, it will be used here: https://github.com/andrius-pra/vscode-ng-language-service/blob/0d810242c580a10907e5acc9d5f0dad36b73ccd5/client/src/extension.ts#L53-L57

**Comment by andrius-pra** [comment]
> Could we send a notification to finish the loading indicator in case the language service throws, without the new `ProjectLoadingNotificationService` class?

Done

File: client/src/project_loading_notification_service.ts (hunk 1 above)
Comment (andrius-pra) [reply client/src/project_loading_notification_service.ts]: It seems doesn't work as I expected. I had disabled extension during project loading, but nothing changed. Loading status disappeared when project had loaded.
I removed this class.

File: integration/lsp/smoke_spec.ts [hunk 3]
```diff
@@ -54,7 +54,11 @@ describe('Angular Language Service', () => {
     });
     server.on('message', (data: Message) => {
       if (isNotificationMessage(data)) {
-        console.log('[server]', data.params.message);
+        if (data.params && data.params.message) {
+          console.log('[server]', data.method, data.params.message);
+        } else {
+          console.log('[server]', data.method);
+        }
```
Comment (ayazhafiz) [inline integration/lsp/smoke_spec.ts]: can we conditionally log on the message? e.g.

```typescript
const toLog = ['[server]', data.method];
if (data.params && data.params.message) toLog.push(data.params.message);
console.log(...toLog);
```

or

```typescript
console.log('[server]', data.method);
if (data.params && data.params.message) console.log(data.params.message);
```

Comment (andrius-pra) [reply integration/lsp/smoke_spec.ts]: Changed to 1st suggestion.
