### PR TITLE
fix: check that a language service exists for discovered projects

### LINKED ISSUE #557: Server shutdown: TypeError: Cannot read property 'getSemanticDiagnostics' of undefined
**Describe the bug**

The Angular Language Service crashes

**To Reproduce**

Exact repro steps are a bit tricky. It seems to happen about 5-10 minutes after I open Visual Studio Code. Before it crashes, I'm also unable to navigate from a html file to a component defined in the html file. 

**Expected behavior**
No crash

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)
```
[Info  - 16:03:16] Angular language server process ID: 7832
[Info  - 16:03:16] Using typescript v3.6.4 from c:\Users\USERNAME\.vscode\extensions\angular.ng-template-0.900.4\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 16:03:16] Using @angular/language-service v9.0.0-rc.8 from c:\Users\USERNAME\.vscode\extensions\angular.ng-template-0.900.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js
[Info  - 16:03:16] Log file: c:\Users\USERNAME\AppData\Roaming\Code\logs\20200116T160301\exthost1\Angular.ng-template\nglangsvc.log
[Error - 16:04:43] No config file for c:\git\MYAPP.FrontEnd\MYAPP\.storybook\preview-head.html
c:\Users\USERNAME\.vscode\extensions\angular.ng-template-0.900.4\server\index.js:1010
	            const diagnostics = ngLS.getSemanticDiagnostics(fileName);
	                                     ^

TypeError: Cannot read property 'getSemanticDiagnostics' of undefined
    at Session.sendPendingDiagnostics (c:\Users\USERNAME\.vscode\extensions\angular.ng-template-0.900.4\server\index.js:1010:39)
    at Timeout._onTimeout (c:\Users\USERNAME\.vscode\extensions\angular.ng-template-0.900.4\server\index.js:990:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
^^^ This error repeats about 450 times
```

2. Log file (Path is printed to the console output at startup)
If this is required, please contact me at simondelang@gmail.com

**Screenshots**

None

**Additional context**

Extension version: v0.900.4
@angular/core: 8.2.14

### PR DESCRIPTION
**Pull request by ayazhafiz**
It appears that in some cases, a language service might not exist for a
project (https://github.com/microsoft/TypeScript/blob/d2c5d54242c69effbed0ebb27033047e0c995589/src/testRunner/unittests/tsserver/typingsInstaller.ts#L1951)
even if the `languageServiceEnabled` property on the project is `true`
(#557). To fix this, bail out of providing language service features
anytime a language service is not found by performing a strict null
check.

Closes #557.

### CODE REVIEW

File: server/src/session.ts [hunk 1]
```diff
@@ -134,10 +134,11 @@ export class Session {
         continue;
       }
       const project = this.projectService.getDefaultProjectForScriptInfo(scriptInfo);
-      if (!project || !project.languageServiceEnabled) {
+      const ngLS = project ?.getLanguageService();
```
Comment (kyliau) [inline server/src/session.ts]: `getLanguageService` will not return undefined if the language service is disabled, so the check for `languageServiceEnabled` is still needed.

Comment (kyliau) [reply server/src/session.ts]: https://github.com/microsoft/TypeScript/blob/bc1e7728df93cfbd70ab2966b37952d5978ba677/src/server/project.ts#L549-L553
