### PR TITLE
fix(server): filter unsupported code action

### LINKED ISSUE #1828: Performance weak. I see the »Getting code actions from …« message almost always
Type: <b>Bug</b>

It happens almost always when I enable »Angular Language Service«. Rarely, when I disable the extension. 

If I can help with any more information (e.g. if it happens after certain config changes), please feel free to give me any hints on what to do. 

Tested it on M1 MacBook, Intel MacBook as well as a Win machine.

M1 Mac specs:

Extension version: 15.0.1
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:22:48.959Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|45, 31, 24|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|. --crash-reporter-id a5c7819b-1ec1-4c37-a353-9dec052ab101|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380

```

</details>

### PR DESCRIPTION
**Pull request by ivanwonder**
Now the Angular code action provider only supports `QuickFix`. If leave the `codeActionKinds` empty, all action requests will be sent to the Angular language service, especially for the action before saving the file, the Angular code action provider will try to fix all errors in the whole file, it's expensive.

Fixes #1828

### CODE REVIEW

File: server/src/session.ts [hunk 1]
```diff
@@ -743,6 +743,11 @@ export class Session {
         },
         codeActionProvider: this.ivy ? {
           resolveProvider: true,
+          // Now the Angular code action provider only supports `QuickFix`. If leave the
+          // `codeActionKinds` empty, all action requests will be sent to the Angular language
+          // service, especially for the action before saving the file, the Angular code action
+          // provider will try to fix all errors in the whole file, it's expensive.
```
Comment (atscott) [inline server/src/session.ts:749]: nit: could you also reference the [issue](https://github.com/angular/vscode-ng-language-service/issues/1828) in the comment here so it can be easily looked up

**Review by atscott — APPROVED** [review]
Thanks for fixing this! We definitely didn't have the historical context to know about this option.

**Comment by dylhunn** [comment]
Thanks Ivan. This would have been really hard to figure out!

**Comment by ivanwonder** [comment]
BTW, the user also can send the quick fix action before saving, but I think it's not expected.

For example, In the built-in typescript extension.

```json
"editor.codeActionsOnSave": {
  "quickfix": true,
}
```
```ts
class Test {
    test() {
        this.missingMember
    }
}
```
After the user saves the file.
```ts
class Test {
    [x: string]: any;
    missingMember: any;
    test() {
        this.missingMember
    }
}
```

**Review by atscott — APPROVED** [review]
