### PR TITLE
Suggest strict templates

### LINKED ISSUE #1053: Prompt users to enable strictTemplates
Ivy language service works best when `fullTemplateTypeCheck` is enabled. This flag could be provided in `angularCompilerOptions` in `tsconfig.json`.

If the flag is not on, some features (go to definition, hover, etc) might not work in certain situations, because the necessary type information is not present in the typecheck files.

This could be confusing or even misleading for users because they would think the language service is broken.

When this flag is not turned on, we need to tell users that language service is not working at its full capability.

There are a few ways we could do this:
1. Show a pop-up window in the editor at startup
2. Show a diagnostic message when user tries to perform an operation but get no results.
3. Show a hint in user's code.

## Show a pop-up window in the editor

Screen Shot 2021-01-07 at 1 26 52 PM

Pro: easiest to implement
Con: could be a little distracting since this is shown every time the project is loaded

Necessary work:
1. Expose the Angular compiler options to the language server
2. Language server sends a notification to the client
3. Client shows the message in a pop up

## Show a diagnostic message when user tries to perform an operation

Screen Shot 2021-01-07 at 1 34 18 PM

Show an `Information` diagnostic when users try to perform an operation but get no results.
This diagnostic will show up in the "Problems" panel.

Pro: Less distracting, because diagnostic is only shown when user tries to do something.
Pro: Does not involve client / server, this is purely on the language service side.
Con: Not straightforward to implement

## Show a hint in user's code

This is similar to the diagnostic approach, except the message does not show up in the "Problems" panel.
The message shows up when user hovers over the `...` in the editor.

Screen Shot 2021-01-07 at 1 34 54 PM

Pro: less distracting
Con: Not straightforward to implement

# Bonus
- Add a "quick fix" to automatically update `tsconfig.json` for users.

# Suggestion
I suggest we do (1) since the impact/work ratio is the highest. We could implement (2) or (3) once the core features are stable.

### PR DESCRIPTION
**Pull request by kyliau**
This commit adds a prompt to encourage users turn on `strictTemplates` so
that they can get the most out of Angular language service.

Screen Shot 2021-02-03 at 11 06 10 AM

PR close #1053

### CODE REVIEW

File: client/src/client.ts [hunk 1]
```diff
@@ -104,8 +104,9 @@ export class AngularLanguageClient implements vscode.Disposable {
   }
 }
 
-function registerNotificationHandlers(client: lsp.LanguageClient) {
-  client.onNotification(ProjectLoadingStart, () => {
+function registerNotificationHandlers(
+    client: lsp.LanguageClient, context: vscode.ExtensionContext) {
+  const d1 = client.onNotification(ProjectLoadingStart, () => {
```
Comment (atscott) [inline client/src/client.ts:109]: nit: d1 and d2 aren't great good variable names

File: client/src/client.ts [hunk 2]
```diff
@@ -116,6 +117,19 @@ function registerNotificationHandlers(client: lsp.LanguageClient) {
         }),
     );
   });
+
+  const d2 = client.onNotification(SuggestStrictMode, async (params: SuggestStrictModeParams) => {
+    const selection = await vscode.window.showInformationMessage(
+        params.message,
+        'Open tsconfig.json',
+    );
+    if (selection) {
```
Comment (atscott) [inline client/src/client.ts:126]:
```suggestion
    const openTsConfig = 'Open tsconfig.json';
    const selection = await vscode.window.showInformationMessage(
        params.message,
        openTsConfig,
    );
    if (selection === openTsConfig) {
```
While I know the API for `showInformationMessage`, I think this might be a bit more clear. WDYT?

File: server/src/session.ts [hunk 3]
```diff
@@ -201,6 +201,23 @@ export class Session {
     project.getLanguageService().getSemanticDiagnostics(fileName);
   }
 
+  private suggestStrictMode(project: ts.server.Project) {
```
Comment (atscott) [inline server/src/session.ts:204]:
```suggestion
  private handleCompilerOptionsDiagnostics(project: ts.server.Project) {
```
What do you think of making this function name a bit more generic?

**Review by atscott — APPROVED** [review]
👍  Nice

File: client/src/client.ts (hunk 1 above)
Comment (kyliau) [reply client/src/client.ts:109]: renamed to `disposable1` and `disposable2`.

**Review by atscott — APPROVED** [review]
